/*Package example provides an example resolver that's autogenerated by
gqlgen.

If adding any new queries, subscriptions, or mutations, the resolver will
likely change. In that case, make sure the actual resolver under package models
is modified to match the interface as shown in the example.
*/
package example

// MutationResolver ...
type MutationResolver interface{}

// QueryResolver ...
type QueryResolver interface{}

// SubscriptionResolver ...
type SubscriptionResolver interface{}
