// Code generated by counterfeiter. DO NOT EDIT.
package modelsfakes

import (
	"context"
	"sync"

	"github.com/ff14wed/aetherometer/core/models"
)

type FakeAuthProvider struct {
	AuthorizePluginTokenStub        func(context.Context) error
	authorizePluginTokenMutex       sync.RWMutex
	authorizePluginTokenArgsForCall []struct {
		arg1 context.Context
	}
	authorizePluginTokenReturns struct {
		result1 error
	}
	authorizePluginTokenReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeAuthProvider) AuthorizePluginToken(arg1 context.Context) error {
	fake.authorizePluginTokenMutex.Lock()
	ret, specificReturn := fake.authorizePluginTokenReturnsOnCall[len(fake.authorizePluginTokenArgsForCall)]
	fake.authorizePluginTokenArgsForCall = append(fake.authorizePluginTokenArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	fake.recordInvocation("AuthorizePluginToken", []interface{}{arg1})
	fake.authorizePluginTokenMutex.Unlock()
	if fake.AuthorizePluginTokenStub != nil {
		return fake.AuthorizePluginTokenStub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	fakeReturns := fake.authorizePluginTokenReturns
	return fakeReturns.result1
}

func (fake *FakeAuthProvider) AuthorizePluginTokenCallCount() int {
	fake.authorizePluginTokenMutex.RLock()
	defer fake.authorizePluginTokenMutex.RUnlock()
	return len(fake.authorizePluginTokenArgsForCall)
}

func (fake *FakeAuthProvider) AuthorizePluginTokenCalls(stub func(context.Context) error) {
	fake.authorizePluginTokenMutex.Lock()
	defer fake.authorizePluginTokenMutex.Unlock()
	fake.AuthorizePluginTokenStub = stub
}

func (fake *FakeAuthProvider) AuthorizePluginTokenArgsForCall(i int) context.Context {
	fake.authorizePluginTokenMutex.RLock()
	defer fake.authorizePluginTokenMutex.RUnlock()
	argsForCall := fake.authorizePluginTokenArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeAuthProvider) AuthorizePluginTokenReturns(result1 error) {
	fake.authorizePluginTokenMutex.Lock()
	defer fake.authorizePluginTokenMutex.Unlock()
	fake.AuthorizePluginTokenStub = nil
	fake.authorizePluginTokenReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeAuthProvider) AuthorizePluginTokenReturnsOnCall(i int, result1 error) {
	fake.authorizePluginTokenMutex.Lock()
	defer fake.authorizePluginTokenMutex.Unlock()
	fake.AuthorizePluginTokenStub = nil
	if fake.authorizePluginTokenReturnsOnCall == nil {
		fake.authorizePluginTokenReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.authorizePluginTokenReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeAuthProvider) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.authorizePluginTokenMutex.RLock()
	defer fake.authorizePluginTokenMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeAuthProvider) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ models.AuthProvider = new(FakeAuthProvider)
