matrix:
  include:
    - language: go
      go:
        - 1.x
      env:
        - GO111MODULE=on
      install:
        - go get -u github.com/onsi/ginkgo/ginkgo
      before_script:
        - cd core
      script:
        - $GOPATH/bin/ginkgo -r -p --randomizeAllSpecs --failOnPending --randomizeSuites --race
