version: 0.3.0.{build}

platform: x64

branches:
  only:
    - master

clone_folder: c:\gopath\src\github.com\ff14wed\aetherometer

environment:
  GOPATH: c:\gopath
  nodejs_version: "Current"

install:
  - echo %PATH%
  - echo %GOPATH%
  - set PATH=%GOPATH%\bin;c:\go\bin;%PATH%
  - go version
  - go env
  - git clone https://github.com/go-task/task
  - pushd task && go install -v ./cmd/task && popd
  - ps: Install-Product node $env:nodejs_version x64

build_script:
  - task build

artifacts:
  - path: dist/aetherometer-*.zip
    name: bundle
    type: zip

init:
  # Set "build version number" to "short-commit-hash" or when tagged to "tag name" (Travis style)
  - ps: >-
      if ($env:APPVEYOR_REPO_TAG -eq "true")
      {
          Update-AppveyorBuild -Version "$($env:APPVEYOR_REPO_TAG_NAME.TrimStart("v"))"
      }
      else
      {
          Update-AppveyorBuild -Version "dev-$($env:APPVEYOR_REPO_COMMIT.Substring(0, 7))"
      }
