version: 0.3.0.{build}

platform: x64

branches:
  only:
    - master

clone_folder: c:\gopath\src\github.com\ff14wed\aetherometer

environment:
  GOPATH: c:\gopath
  nodejs_version: "Current"

install:
  - echo %PATH%
  - echo %GOPATH%
  - set PATH=%GOPATH%\bin;c:\go\bin;%PATH%
  - go version
  - go env
  - git clone https://github.com/go-task/taskt
  - cd task
  - go install -v ./cmd/task
  - ps: Install-Product node $env:nodejs_version x64

build_script:
  - task build

artifacts:
  - path: dist/aetherometer-*.zip
    name: bundle
    type: zip
