version: '3'

vars:
  NODE_OS: '{{if eq OS "windows"}}win{{else if eq OS "darwin"}}mac{{else}}{{OS}}{{end}}'
  TASKDIR:
    sh: pwd
  CORE_OUTPUT: "{{.TASKDIR}}/resources/{{.NODE_OS}}/core{{exeExt}}"
  CORE_OUTPUT_WIN: "{{.TASKDIR}}/resources/win/core.exe"
  CORE_BUILD_FLAGS: '-trimpath -ldflags="-s -w"'

tasks:
  build-core:
    dir: core
    cmds:
      - go build -o '{{fromSlash .CORE_OUTPUT}}' {{.CORE_BUILD_FLAGS}} main.go

  # For building for Windows on a non-Windows platform
  build-core-windows:
    env:
      GOOS: windows
    dir: core
    cmds:
      - go build -o '{{fromSlash .CORE_OUTPUT_WIN}}' {{.CORE_BUILD_FLAGS}} main.go

  build-ui:
    dir: ui
    cmds:
        - yarn install
        - yarn run electron:build

  install-rimraf:
    cmds:
      - yarn global add rimraf

  clean:
    deps:
      - install-rimraf
    vars:
      PATH_SEP: '{{if eq OS "windows"}};{{else}}:{{end}}'
      YARN_GLOBAL_BIN:
        sh:
          yarn global bin
    env:
      PATH: '{{.YARN_GLOBAL_BIN}}{{.PATH_SEP}}{{env "PATH"}}'
    cmds:
      - go clean
      - rimraf '{{fromSlash .CORE_OUTPUT}}'
      - rimraf '{{fromSlash .CORE_OUTPUT_WIN}}'
      - rimraf '{{.TASKDIR}}{{fromSlash "/dist"}}'
      - rimraf '{{.TASKDIR}}{{fromSlash "/ui/dist_electron"}}'

  build:
    cmds:
      - task: build-core
      - task: build-ui

  rebuild:
    cmds:
      - task: clean
      - task: build
