// Code generated by counterfeiter. DO NOT EDIT.
package streamfakes

import (
	"sync"

	"github.com/ff14wed/sibyl/backend/stream"
	xivnet "github.com/ff14wed/xivnet/v3"
)

type FakeProvider struct {
	PIDStub        func() int
	pIDMutex       sync.RWMutex
	pIDArgsForCall []struct {
	}
	pIDReturns struct {
		result1 int
	}
	pIDReturnsOnCall map[int]struct {
		result1 int
	}
	SendRequestStub        func([]byte) ([]byte, error)
	sendRequestMutex       sync.RWMutex
	sendRequestArgsForCall []struct {
		arg1 []byte
	}
	sendRequestReturns struct {
		result1 []byte
		result2 error
	}
	sendRequestReturnsOnCall map[int]struct {
		result1 []byte
		result2 error
	}
	SubscribeEgressStub        func() <-chan *xivnet.Frame
	subscribeEgressMutex       sync.RWMutex
	subscribeEgressArgsForCall []struct {
	}
	subscribeEgressReturns struct {
		result1 <-chan *xivnet.Frame
	}
	subscribeEgressReturnsOnCall map[int]struct {
		result1 <-chan *xivnet.Frame
	}
	SubscribeIngressStub        func() <-chan *xivnet.Frame
	subscribeIngressMutex       sync.RWMutex
	subscribeIngressArgsForCall []struct {
	}
	subscribeIngressReturns struct {
		result1 <-chan *xivnet.Frame
	}
	subscribeIngressReturnsOnCall map[int]struct {
		result1 <-chan *xivnet.Frame
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeProvider) PID() int {
	fake.pIDMutex.Lock()
	ret, specificReturn := fake.pIDReturnsOnCall[len(fake.pIDArgsForCall)]
	fake.pIDArgsForCall = append(fake.pIDArgsForCall, struct {
	}{})
	fake.recordInvocation("PID", []interface{}{})
	fake.pIDMutex.Unlock()
	if fake.PIDStub != nil {
		return fake.PIDStub()
	}
	if specificReturn {
		return ret.result1
	}
	fakeReturns := fake.pIDReturns
	return fakeReturns.result1
}

func (fake *FakeProvider) PIDCallCount() int {
	fake.pIDMutex.RLock()
	defer fake.pIDMutex.RUnlock()
	return len(fake.pIDArgsForCall)
}

func (fake *FakeProvider) PIDCalls(stub func() int) {
	fake.pIDMutex.Lock()
	defer fake.pIDMutex.Unlock()
	fake.PIDStub = stub
}

func (fake *FakeProvider) PIDReturns(result1 int) {
	fake.pIDMutex.Lock()
	defer fake.pIDMutex.Unlock()
	fake.PIDStub = nil
	fake.pIDReturns = struct {
		result1 int
	}{result1}
}

func (fake *FakeProvider) PIDReturnsOnCall(i int, result1 int) {
	fake.pIDMutex.Lock()
	defer fake.pIDMutex.Unlock()
	fake.PIDStub = nil
	if fake.pIDReturnsOnCall == nil {
		fake.pIDReturnsOnCall = make(map[int]struct {
			result1 int
		})
	}
	fake.pIDReturnsOnCall[i] = struct {
		result1 int
	}{result1}
}

func (fake *FakeProvider) SendRequest(arg1 []byte) ([]byte, error) {
	var arg1Copy []byte
	if arg1 != nil {
		arg1Copy = make([]byte, len(arg1))
		copy(arg1Copy, arg1)
	}
	fake.sendRequestMutex.Lock()
	ret, specificReturn := fake.sendRequestReturnsOnCall[len(fake.sendRequestArgsForCall)]
	fake.sendRequestArgsForCall = append(fake.sendRequestArgsForCall, struct {
		arg1 []byte
	}{arg1Copy})
	fake.recordInvocation("SendRequest", []interface{}{arg1Copy})
	fake.sendRequestMutex.Unlock()
	if fake.SendRequestStub != nil {
		return fake.SendRequestStub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	fakeReturns := fake.sendRequestReturns
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeProvider) SendRequestCallCount() int {
	fake.sendRequestMutex.RLock()
	defer fake.sendRequestMutex.RUnlock()
	return len(fake.sendRequestArgsForCall)
}

func (fake *FakeProvider) SendRequestCalls(stub func([]byte) ([]byte, error)) {
	fake.sendRequestMutex.Lock()
	defer fake.sendRequestMutex.Unlock()
	fake.SendRequestStub = stub
}

func (fake *FakeProvider) SendRequestArgsForCall(i int) []byte {
	fake.sendRequestMutex.RLock()
	defer fake.sendRequestMutex.RUnlock()
	argsForCall := fake.sendRequestArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeProvider) SendRequestReturns(result1 []byte, result2 error) {
	fake.sendRequestMutex.Lock()
	defer fake.sendRequestMutex.Unlock()
	fake.SendRequestStub = nil
	fake.sendRequestReturns = struct {
		result1 []byte
		result2 error
	}{result1, result2}
}

func (fake *FakeProvider) SendRequestReturnsOnCall(i int, result1 []byte, result2 error) {
	fake.sendRequestMutex.Lock()
	defer fake.sendRequestMutex.Unlock()
	fake.SendRequestStub = nil
	if fake.sendRequestReturnsOnCall == nil {
		fake.sendRequestReturnsOnCall = make(map[int]struct {
			result1 []byte
			result2 error
		})
	}
	fake.sendRequestReturnsOnCall[i] = struct {
		result1 []byte
		result2 error
	}{result1, result2}
}

func (fake *FakeProvider) SubscribeEgress() <-chan *xivnet.Frame {
	fake.subscribeEgressMutex.Lock()
	ret, specificReturn := fake.subscribeEgressReturnsOnCall[len(fake.subscribeEgressArgsForCall)]
	fake.subscribeEgressArgsForCall = append(fake.subscribeEgressArgsForCall, struct {
	}{})
	fake.recordInvocation("SubscribeEgress", []interface{}{})
	fake.subscribeEgressMutex.Unlock()
	if fake.SubscribeEgressStub != nil {
		return fake.SubscribeEgressStub()
	}
	if specificReturn {
		return ret.result1
	}
	fakeReturns := fake.subscribeEgressReturns
	return fakeReturns.result1
}

func (fake *FakeProvider) SubscribeEgressCallCount() int {
	fake.subscribeEgressMutex.RLock()
	defer fake.subscribeEgressMutex.RUnlock()
	return len(fake.subscribeEgressArgsForCall)
}

func (fake *FakeProvider) SubscribeEgressCalls(stub func() <-chan *xivnet.Frame) {
	fake.subscribeEgressMutex.Lock()
	defer fake.subscribeEgressMutex.Unlock()
	fake.SubscribeEgressStub = stub
}

func (fake *FakeProvider) SubscribeEgressReturns(result1 <-chan *xivnet.Frame) {
	fake.subscribeEgressMutex.Lock()
	defer fake.subscribeEgressMutex.Unlock()
	fake.SubscribeEgressStub = nil
	fake.subscribeEgressReturns = struct {
		result1 <-chan *xivnet.Frame
	}{result1}
}

func (fake *FakeProvider) SubscribeEgressReturnsOnCall(i int, result1 <-chan *xivnet.Frame) {
	fake.subscribeEgressMutex.Lock()
	defer fake.subscribeEgressMutex.Unlock()
	fake.SubscribeEgressStub = nil
	if fake.subscribeEgressReturnsOnCall == nil {
		fake.subscribeEgressReturnsOnCall = make(map[int]struct {
			result1 <-chan *xivnet.Frame
		})
	}
	fake.subscribeEgressReturnsOnCall[i] = struct {
		result1 <-chan *xivnet.Frame
	}{result1}
}

func (fake *FakeProvider) SubscribeIngress() <-chan *xivnet.Frame {
	fake.subscribeIngressMutex.Lock()
	ret, specificReturn := fake.subscribeIngressReturnsOnCall[len(fake.subscribeIngressArgsForCall)]
	fake.subscribeIngressArgsForCall = append(fake.subscribeIngressArgsForCall, struct {
	}{})
	fake.recordInvocation("SubscribeIngress", []interface{}{})
	fake.subscribeIngressMutex.Unlock()
	if fake.SubscribeIngressStub != nil {
		return fake.SubscribeIngressStub()
	}
	if specificReturn {
		return ret.result1
	}
	fakeReturns := fake.subscribeIngressReturns
	return fakeReturns.result1
}

func (fake *FakeProvider) SubscribeIngressCallCount() int {
	fake.subscribeIngressMutex.RLock()
	defer fake.subscribeIngressMutex.RUnlock()
	return len(fake.subscribeIngressArgsForCall)
}

func (fake *FakeProvider) SubscribeIngressCalls(stub func() <-chan *xivnet.Frame) {
	fake.subscribeIngressMutex.Lock()
	defer fake.subscribeIngressMutex.Unlock()
	fake.SubscribeIngressStub = stub
}

func (fake *FakeProvider) SubscribeIngressReturns(result1 <-chan *xivnet.Frame) {
	fake.subscribeIngressMutex.Lock()
	defer fake.subscribeIngressMutex.Unlock()
	fake.SubscribeIngressStub = nil
	fake.subscribeIngressReturns = struct {
		result1 <-chan *xivnet.Frame
	}{result1}
}

func (fake *FakeProvider) SubscribeIngressReturnsOnCall(i int, result1 <-chan *xivnet.Frame) {
	fake.subscribeIngressMutex.Lock()
	defer fake.subscribeIngressMutex.Unlock()
	fake.SubscribeIngressStub = nil
	if fake.subscribeIngressReturnsOnCall == nil {
		fake.subscribeIngressReturnsOnCall = make(map[int]struct {
			result1 <-chan *xivnet.Frame
		})
	}
	fake.subscribeIngressReturnsOnCall[i] = struct {
		result1 <-chan *xivnet.Frame
	}{result1}
}

func (fake *FakeProvider) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.pIDMutex.RLock()
	defer fake.pIDMutex.RUnlock()
	fake.sendRequestMutex.RLock()
	defer fake.sendRequestMutex.RUnlock()
	fake.subscribeEgressMutex.RLock()
	defer fake.subscribeEgressMutex.RUnlock()
	fake.subscribeIngressMutex.RLock()
	defer fake.subscribeIngressMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeProvider) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ stream.Provider = new(FakeProvider)
