// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

type Action struct {
	ID        int    `json:"id"`
	Name      string `json:"name"`
	TargetID  int    `json:"targetID"`
	UseTimeMs int    `json:"useTimeMs"`
}

type CastingInfo struct {
	ActionID      int      `json:"actionID"`
	ActionName    string   `json:"actionName"`
	StartTimeMs   int      `json:"startTimeMs"`
	CastTimeMs    int      `json:"castTimeMs"`
	TargetID      int      `json:"targetID"`
	Location      Location `json:"location"`
	CastType      int      `json:"castType"`
	EffectRange   int      `json:"effectRange"`
	XAxisModifier int      `json:"xAxisModifier"`
	Omen          string   `json:"omen"`
}

type CraftingInfo struct {
	LastCraftAction   int `json:"lastCraftAction"`
	StepNum           int `json:"stepNum"`
	TotalProgress     int `json:"totalProgress"`
	ProgressDelta     int `json:"progressDelta"`
	TotalQuality      int `json:"totalQuality"`
	QualityDelta      int `json:"qualityDelta"`
	HqChance          int `json:"hqChance"`
	Durability        int `json:"durability"`
	DurabilityDelta   int `json:"durabilityDelta"`
	CurrentCondition  int `json:"currentCondition"`
	PreviousCondition int `json:"previousCondition"`
}

type Entity struct {
	ID               int          `json:"id"`
	Index            int          `json:"index"`
	Name             string       `json:"name"`
	TargetID         int          `json:"targetID"`
	OwnerID          int          `json:"ownerID"`
	Level            int          `json:"level"`
	Class            int          `json:"class"`
	IsNPC            bool         `json:"isNPC"`
	IsEnemy          bool         `json:"isEnemy"`
	IsPet            bool         `json:"isPet"`
	BNPCInfo         *NPCInfo     `json:"bNPCInfo"`
	Resources        Resources    `json:"resources"`
	Location         Location     `json:"location"`
	LastAction       *Action      `json:"lastAction"`
	Statuses         []Status     `json:"statuses"`
	CastingInfo      *CastingInfo `json:"castingInfo"`
	RawSpawnJSONData string       `json:"rawSpawnJSONData"`
}

type HateEntry struct {
	EnemyID     int `json:"enemyID"`
	HatePercent int `json:"hatePercent"`
}

type HateRanking struct {
	ActorID int `json:"actorID"`
	Hate    int `json:"hate"`
}

type Location struct {
	X             float64 `json:"x"`
	Y             float64 `json:"y"`
	Z             float64 `json:"z"`
	Orientation   float64 `json:"orientation"`
	LastUpdatedMs int     `json:"lastUpdatedMs"`
}

type MapInfo struct {
	Key           int    `json:"key"`
	ID            string `json:"id"`
	SizeFactor    int    `json:"SizeFactor"`
	OffsetX       int    `json:"OffsetX"`
	OffsetY       int    `json:"OffsetY"`
	PlaceName     string `json:"PlaceName"`
	PlaceNameSub  string `json:"PlaceNameSub"`
	TerritoryType string `json:"TerritoryType"`
}

type NPCInfo struct {
	NameID  int      `json:"nameID"`
	BaseID  int      `json:"baseID"`
	ModelID int      `json:"modelID"`
	Name    *string  `json:"name"`
	Size    *float64 `json:"size"`
	Error   int      `json:"error"`
}

type Resources struct {
	Hp         int `json:"hp"`
	Mp         int `json:"mp"`
	Tp         int `json:"tp"`
	MaxHP      int `json:"maxHP"`
	MaxMP      int `json:"maxMP"`
	LastTickMs int `json:"lastTickMs"`
}

type Status struct {
	ID            int    `json:"id"`
	Extra         int    `json:"extra"`
	Name          string `json:"name"`
	StartedTimeMs int    `json:"startedTimeMs"`
	DurationMs    int    `json:"durationMs"`
	ActorID       int    `json:"actorID"`
	LastTickMs    int    `json:"lastTickMs"`
	BaseDamage    int    `json:"baseDamage"`
	CritRate      int    `json:"critRate"`
}
