package testassets

// BNPCBaseJSON ...
var BNPCBaseJSON = `[
  {
    "0": 0,
    "1": 4,
    "10": false,
    "12": 0,
    "13": true,
    "14": true,
    "15": true,
    "16": true,
    "17": 0,
    "2": 0,
    "3": 0,
    "8": 0,
    "9": 0,
    "ArrayEventHandler": "",
    "BNpcCustomize": "BNpcCustomize#0",
    "ModelChara": "ModelChara#0",
    "NpcEquip": "NpcEquip#0",
    "Scale": 1,
    "key": 0
  },
  {
    "0": 0,
    "1": 4,
    "10": false,
    "12": 0,
    "13": true,
    "14": true,
    "15": true,
    "16": true,
    "17": 0,
    "2": 0,
    "3": 0,
    "8": 0,
    "9": 0,
    "ArrayEventHandler": "",
    "BNpcCustomize": "BNpcCustomize#2",
    "ModelChara": "ModelChara#0",
    "NpcEquip": "NpcEquip#366",
    "Scale": 1,
    "key": 1
  },
  {
    "0": 0,
    "1": 4,
    "10": false,
    "12": 0,
    "13": true,
    "14": true,
    "15": true,
    "16": true,
    "17": 0,
    "2": 0,
    "3": 0,
    "8": 0,
    "9": 0,
    "ArrayEventHandler": "ArrayEventHandler#851976",
    "BNpcCustomize": "BNpcCustomize#0",
    "ModelChara": "ModelChara#96",
    "NpcEquip": "NpcEquip#0",
    "Scale": 1,
    "key": 2
  },
  {
    "0": 0,
    "1": 4,
    "10": false,
    "12": 0,
    "13": true,
    "14": true,
    "15": true,
    "16": true,
    "17": 0,
    "2": 0,
    "3": 0,
    "8": 0,
    "9": 0,
    "ArrayEventHandler": "ArrayEventHandler#852023",
    "BNpcCustomize": "BNpcCustomize#0",
    "ModelChara": "ModelChara#61",
    "NpcEquip": "NpcEquip#0",
    "Scale": 1.2,
    "key": 3
  }
]`
