package testassets

// MapJSON ...
var MapJSON = `[
  {
    "0": 0,
    "1": 0,
    "13": 0,
    "16": false,
    "2": "0",
    "DiscoveryArrayByte": true,
    "DiscoveryIndex": -1,
    "Hierarchy": 0,
    "Id": "",
    "MapMarkerRange": 0,
    "Offset{X}": 0,
    "Offset{Y}": 0,
    "PlaceName": "",
    "PlaceName{Region}": "",
    "PlaceName{Sub}": "",
    "SizeFactor": 100,
    "TerritoryType": "",
    "key": 0
  },
  {
    "0": 0,
    "1": 0,
    "13": 0,
    "16": false,
    "2": "0",
    "DiscoveryArrayByte": true,
    "DiscoveryIndex": -1,
    "Hierarchy": 1,
    "Id": "default/00",
    "MapMarkerRange": 0,
    "Offset{X}": 0,
    "Offset{Y}": 0,
    "PlaceName": "Eorzea",
    "PlaceName{Region}": "???",
    "PlaceName{Sub}": "",
    "SizeFactor": 100,
    "TerritoryType": "",
    "key": 1
  },
  {
    "0": 2,
    "1": 2,
    "13": 0,
    "16": false,
    "2": "0",
    "DiscoveryArrayByte": true,
    "DiscoveryIndex": -1,
    "Hierarchy": 1,
    "Id": "f1t1/00",
    "MapMarkerRange": 3,
    "Offset{X}": 0,
    "Offset{Y}": 0,
    "PlaceName": "New Gridania",
    "PlaceName{Region}": "The Black Shroud",
    "PlaceName{Sub}": "",
    "SizeFactor": 200,
    "TerritoryType": "f1t1",
    "key": 2
  },
  {
    "0": 2,
    "1": 3,
    "13": 0,
    "16": false,
    "2": "0",
    "DiscoveryArrayByte": true,
    "DiscoveryIndex": -1,
    "Hierarchy": 1,
    "Id": "f1t2/00",
    "MapMarkerRange": 4,
    "Offset{X}": 0,
    "Offset{Y}": 0,
    "PlaceName": "Old Gridania",
    "PlaceName{Region}": "The Black Shroud",
    "PlaceName{Sub}": "",
    "SizeFactor": 200,
    "TerritoryType": "f1t2",
    "key": 3
  },
  {
    "0": 3,
    "1": 3,
    "13": 0,
    "16": false,
    "2": "1",
    "DiscoveryArrayByte": true,
    "DiscoveryIndex": -1,
    "Hierarchy": 1,
    "Id": "w1t2/01",
    "MapMarkerRange": 60,
    "Offset{X}": 0,
    "Offset{Y}": 0,
    "PlaceName": "Ul'dah - Steps of Thal",
    "PlaceName{Region}": "Thanalan",
    "PlaceName{Sub}": "Merchant Strip",
    "SizeFactor": 200,
    "TerritoryType": "w1t2",
    "key": 14
  },
  {
    "0": 3,
    "1": 3,
    "13": 0,
    "16": false,
    "2": "2",
    "DiscoveryArrayByte": true,
    "DiscoveryIndex": -1,
    "Hierarchy": 1,
    "Id": "w1t2/02",
    "MapMarkerRange": 62,
    "Offset{X}": 0,
    "Offset{Y}": 0,
    "PlaceName": "Ul'dah - Steps of Thal",
    "PlaceName{Region}": "Thanalan",
    "PlaceName{Sub}": "Hustings Strip",
    "SizeFactor": 200,
    "TerritoryType": "w1t2",
    "key": 73
  },
  {
    "0": 0,
    "1": 0,
    "13": 0,
    "16": false,
    "2": "0",
    "DiscoveryArrayByte": true,
    "DiscoveryIndex": -1,
    "Hierarchy": 1,
    "Id": "w1b4/00",
    "MapMarkerRange": 143,
    "Offset{X}": -448,
    "Offset{Y}": 0,
    "PlaceName": "The Burning Heart",
    "PlaceName{Region}": "Thanalan",
    "PlaceName{Sub}": "",
    "SizeFactor": 200,
    "TerritoryType": "w1b4",
    "key": 178
  },
  {
    "0": 0,
    "1": 0,
    "13": 0,
    "16": false,
    "2": "0",
    "DiscoveryArrayByte": true,
    "DiscoveryIndex": -1,
    "Hierarchy": 1,
    "Id": "s1fa/00",
    "MapMarkerRange": 0,
    "Offset{X}": 0,
    "Offset{Y}": 0,
    "PlaceName": "The Navel",
    "PlaceName{Region}": "La Noscea",
    "PlaceName{Sub}": "",
    "SizeFactor": 400,
    "TerritoryType": "s1fa",
    "key": 33
  },
  {
    "0": 0,
    "1": 0,
    "13": 0,
    "16": false,
    "2": 0,
    "DiscoveryArrayByte": true,
    "DiscoveryIndex": -1,
    "Hierarchy": 1,
    "Id": "s1fa/00",
    "MapMarkerRange": 0,
    "Offset{X}": 0,
    "Offset{Y}": 0,
    "PlaceName": "The Navel",
    "PlaceName{Region}": "La Noscea",
    "PlaceName{Sub}": "",
    "SizeFactor": 400,
    "TerritoryType": "s1fa_2",
    "key": 403
  }
]`
