name: Build and Release
on:
  push:
    tags:
    - v*

jobs:
  build:
    runs-on: windows-2019
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Use Node.js 17
      uses: actions/setup-node@v2
      with:
        node-version: 17.x

    - name: Install Wails
      run: go install github.com/wailsapp/wails/v2/cmd/wails@latest

    - uses: actions/checkout@v3

    - name: Build
      run: |
        wails build -f -ldflags "-X main.Version=${{ github.ref_name }}"

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: aetherometer-windows
        path: build/bin/aetherometer.exe

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v3

    - name: zip exe for release
      run: zip aetherometer-windows-amd64.zip ./aetherometer-windows/aetherometer.exe

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        name: Aetherometer ${{ github.ref_name }}
        body: "# What's changed"
        draft: true
        files: aetherometer-windows-amd64.zip
